services:
  database:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: go_book_store_api
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data